In [9]:
import pandas as pd

df = pd.read_csv('universal_top_spotify_songs.csv')
df = df.drop(columns=['spotify_id', 'daily_rank', 'daily_movement', 'weekly_movement', 'snapshot_date', 'name', 'album_release_date', 'album_name'])

countries = ['GB', 'DE', 'FR', 'ES', 'IT', 'NL', 'SE', 'PL', 'BE', 'PT']

df = df[df['country'].isin(countries)]
df = df.groupby('country').head(500)


df

,artists,country,popularity,is_explicit,duration_ms,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
650,"Tjuvjakt, Fanny Avonne",SE,76,False,190344,0.735,0.6530,3,-6.261,1,0.0533,0.3600,0.000000,0.0791,0.620,116.002,4
651,Ida-Lova,SE,77,False,187076,0.404,0.6830,1,-6.969,1,0.0594,0.3020,0.000000,0.3180,0.661,162.091,4
652,Lov1,SE,64,False,208201,0.695,0.6760,8,-6.859,1,0.0384,0.1010,0.000000,0.0929,0.431,121.962,4
653,KAJ,SE,75,False,166880,0.757,0.8890,9,-4.729,0,0.0788,0.0754,0.000023,0.0397,0.754,106.037,4
654,"Humlan Djojj, Josefine Götestam",SE,76,False,140046,0.684,0.0326,0,-17.898,1,0.0583,0.9730,0.000002,0.1080,0.440,66.685,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
467263,Chappell Roan,GB,48,False,184841,0.742,0.7570,6,-4.981,1,0.0421,0.0187,0.000000,0.3050,0.957,139.982,4
467264,Central Cee,GB,36,True,198400,0.750,0.7370,11,-4.245,0,0.3000,0.4450,0.000000,0.0772,0.962,142.402,4
467265,Myles Smith,GB,75,False,176000,0.762,0.7830,5,-5.206,0,0.0387,0.3290,0.000000,0.0536,0.840,115.091,4
467266,"PAWSA, The Adventures Of Stevie V",GB,81,False,221448,0.783,0.4730,0,-6.493,1,0.1670,0.0693,0.000034,0.1490,0.539,131.890,4
467267,"Kendrick Lamar, SZA",GB,88,False,177598,0.707,0.5750,2,-7.546,1,0.1250,0.2510,0.000000,0.2480,0.576,138.008,4

In [ ]:
df.to_csv('top_spotify_songs_EU_cleaned.csv', index=False) #remove index

In [17]:
##Continued Cleaning

df = pd.read_csv('top_spotify_songs_EU_cleaned.csv')
df.head(5)

,artists,country,popularity,is_explicit,duration_ms,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
0,"Tjuvjakt, Fanny Avonne",SE,76,False,190344,0.735,0.6530,3,-6.261,1,0.0533,0.3600,0.000000,0.0791,0.620,116.002,4
1,Ida-Lova,SE,77,False,187076,0.404,0.6830,1,-6.969,1,0.0594,0.3020,0.000000,0.3180,0.661,162.091,4
2,Lov1,SE,64,False,208201,0.695,0.6760,8,-6.859,1,0.0384,0.1010,0.000000,0.0929,0.431,121.962,4
3,KAJ,SE,75,False,166880,0.757,0.8890,9,-4.729,0,0.0788,0.0754,0.000023,0.0397,0.754,106.037,4
4,"Humlan Djojj, Josefine Götestam",SE,76,False,140046,0.684,0.0326,0,-17.898,1,0.0583,0.9730,0.000002,0.1080,0.440,66.685,5

In [18]:
df['duration_s'] = df['duration_ms'] / 1000
df = df.drop(columns=['duration_ms'])

In [ ]:
df['artist_count'] = df['artists'].str.split(',').str.len()

,artists,country,popularity,is_explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,duration_s,artist_count
0,"Tjuvjakt, Fanny Avonne",SE,76,False,0.735,0.6530,3,-6.261,1,0.0533,0.3600,0.000000,0.0791,0.620,116.002,4,190.344,2
1,Ida-Lova,SE,77,False,0.404,0.6830,1,-6.969,1,0.0594,0.3020,0.000000,0.3180,0.661,162.091,4,187.076,1
2,Lov1,SE,64,False,0.695,0.6760,8,-6.859,1,0.0384,0.1010,0.000000,0.0929,0.431,121.962,4,208.201,1
3,KAJ,SE,75,False,0.757,0.8890,9,-4.729,0,0.0788,0.0754,0.000023,0.0397,0.754,106.037,4,166.880,1
4,"Humlan Djojj, Josefine Götestam",SE,76,False,0.684,0.0326,0,-17.898,1,0.0583,0.9730,0.000002,0.1080,0.440,66.685,5,140.046,2

In [ ]:
print(max(df['artist_count']))
df['artists'] = df['artists'].str.lower()
df['artists_list'] = df['artists'].str.split(', ')

df_exploded = df.explode('artists_list')

7

In [5]:
df.head(5)
df

,artists,country,popularity,is_explicit,duration_ms,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
650,"Tjuvjakt, Fanny Avonne",SE,76,False,190344,0.735,0.6530,3,-6.261,1,0.0533,0.3600,0.000000,0.0791,0.620,116.002,4
651,Ida-Lova,SE,77,False,187076,0.404,0.6830,1,-6.969,1,0.0594,0.3020,0.000000,0.3180,0.661,162.091,4
652,Lov1,SE,64,False,208201,0.695,0.6760,8,-6.859,1,0.0384,0.1010,0.000000,0.0929,0.431,121.962,4
653,KAJ,SE,75,False,166880,0.757,0.8890,9,-4.729,0,0.0788,0.0754,0.000023,0.0397,0.754,106.037,4
654,"Humlan Djojj, Josefine Götestam",SE,76,False,140046,0.684,0.0326,0,-17.898,1,0.0583,0.9730,0.000002,0.1080,0.440,66.685,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
467263,Chappell Roan,GB,48,False,184841,0.742,0.7570,6,-4.981,1,0.0421,0.0187,0.000000,0.3050,0.957,139.982,4
467264,Central Cee,GB,36,True,198400,0.750,0.7370,11,-4.245,0,0.3000,0.4450,0.000000,0.0772,0.962,142.402,4
467265,Myles Smith,GB,75,False,176000,0.762,0.7830,5,-5.206,0,0.0387,0.3290,0.000000,0.0536,0.840,115.091,4
467266,"PAWSA, The Adventures Of Stevie V",GB,81,False,221448,0.783,0.4730,0,-6.493,1,0.1670,0.0693,0.000034,0.1490,0.539,131.890,4
467267,"Kendrick Lamar, SZA",GB,88,False,177598,0.707,0.5750,2,-7.546,1,0.1250,0.2510,0.000000,0.2480,0.576,138.008,4

In [4]:
df.to_csv('fully_cleaned_top_spotify_songs_EU.csv', index=False) #cleaned new df